_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
K_epochs:
    value: 5
action_dim:
    value: 2
actor_dim:
    value:
        - 64
        - 64
actor_lr:
    value: 0.0001
algo_name:
    value: ppo
critic_dim:
    value:
        - 128
        - 128
critic_lr:
    value: 0.0003
device:
    value: cpu
entropy_scaler:
    value: 0.001
episode_len:
    value: 200
eps:
    value: 0.2
eval_episodes:
    value: 10
eval_num:
    value: 10
gae:
    value: null
gamma:
    value: 0.99
gpu_idx:
    value: 0
group:
    value: 03-17_22-18-16.669556-61d7
load_pretrained_model:
    value: false
log_interval:
    value: 50
logdir:
    value: log/train_log/03-17_22-18-16.669556-61d7
minibatch_size:
    value: 64
name:
    value: ppo-car-61d7-seed:1825
num_minibatch:
    value: 8
num_runs:
    value: 10
project:
    value: Exp
seed:
    value: 1825
state_dim:
    value: 4
target_kl:
    value: 0.02
task:
    value: car
timesteps:
    value: 1e+07
use_cuda:
    value: true
